/* Additive SQL Server migration for deployments that run schema changes separately. */
IF OBJECT_ID(N'dbo.VOUCHERS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.VOUCHERS (
    voucher_id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_VOUCHERS PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    code NVARCHAR(50) NOT NULL CONSTRAINT UQ_VOUCHERS_CODE UNIQUE,
    discount_type NVARCHAR(10) NOT NULL CONSTRAINT CK_VOUCHERS_DISCOUNT_TYPE CHECK (discount_type IN ('PERCENTAGE', 'FIXED')),
    discount_value DECIMAL(10, 2) NOT NULL CONSTRAINT CK_VOUCHERS_DISCOUNT_AMOUNT CHECK (discount_value > 0),
    minimum_order_amount DECIMAL(10, 2) NOT NULL CONSTRAINT DF_VOUCHERS_MINIMUM_ORDER_AMOUNT DEFAULT ((0)) CHECK (minimum_order_amount >= 0),
    usage_limit INT NULL CONSTRAINT CK_VOUCHERS_USAGE_LIMIT CHECK (usage_limit IS NULL OR usage_limit > 0),
    usage_count INT NOT NULL CONSTRAINT DF_VOUCHERS_USAGE_COUNT DEFAULT ((0)),
    start_date DATETIME2(7) NOT NULL,
    end_date DATETIME2(7) NOT NULL CONSTRAINT CK_VOUCHERS_DATE_RANGE CHECK (end_date > start_date),
    is_active BIT NOT NULL CONSTRAINT DF_VOUCHERS_IS_ACTIVE DEFAULT ((1)),
    created_at DATETIME2(7) NOT NULL CONSTRAINT DF_VOUCHERS_CREATED_AT DEFAULT (GETDATE()),
    updated_at DATETIME2(7) NULL
  );
END;

IF COL_LENGTH('dbo.ORDERS', 'voucher_id') IS NULL
  ALTER TABLE dbo.ORDERS ADD voucher_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('dbo.ORDERS', 'voucher_code') IS NULL
  ALTER TABLE dbo.ORDERS ADD voucher_code NVARCHAR(50) NULL;
IF COL_LENGTH('dbo.ORDERS', 'voucher_discount') IS NULL
  ALTER TABLE dbo.ORDERS ADD voucher_discount DECIMAL(10, 2) NULL;
IF COL_LENGTH('dbo.ORDERS', 'voucher_discount_amount') IS NULL
  ALTER TABLE dbo.ORDERS ADD voucher_discount_amount DECIMAL(10, 2) NOT NULL CONSTRAINT DF_ORDERS_VOUCHER_DISCOUNT_AMOUNT DEFAULT ((0));

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ORDERS_VOUCHERS')
  ALTER TABLE dbo.ORDERS ADD CONSTRAINT FK_ORDERS_VOUCHERS FOREIGN KEY (voucher_id) REFERENCES dbo.VOUCHERS(voucher_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_VOUCHERS_ACTIVE_DATES' AND object_id = OBJECT_ID('dbo.VOUCHERS'))
  CREATE INDEX IX_VOUCHERS_ACTIVE_DATES ON dbo.VOUCHERS(is_active, start_date, end_date);
